version: '3.8'

services:
  warlock-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warlock-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - "warlock-compose-fs_warlock-network"
    volumes:
      - shared-filestore:/app/filestore

volumes:
  shared-filestore:
    name: shared-filestore
    driver: local

networks:
  warlock-compose-fs_warlock-network:
    external: true
