version: '3.8'

services:
  warlock-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warlock-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - "warlock-compose-ds_warlock-network"

networks:
  warlock-compose-ds_warlock-network:
    external: true
